
const Message=`Sorry to bother you.\nThis message is generated by a human but sent by a bot `;

const generateMessage=(name)=>{
    name=name.trim().split(" ")[0];
    return `Hello ${name},\n${Message}`;
}


export default generateMessage;