
const Message=`This message is generated by a human but sent by a bot `;

const generateMessage=(name)=>{
    name=name.trim().split(" ")[0];
    return `Hey ${name},\n${Message}`;
}


export default generateMessage;